// Temario real por asignatura y nivel: temas con resumen, tarjetas y test.
import { detectGroup, detectBand, type Group, type Band } from "@/lib/study";

export type Flashcard = { front: string; back: string };
export type Unit = {
  id: string;
  title: string;
  summary: string;
  flashcards: Flashcard[];
  quiz: { q: string; options: string[]; answer: number }[];
};

const CURR: Record<Group, Partial<Record<Band, Unit[]>>> = {
  matematicas: {
    primaria: [
      { id: "mp1", title: "Números y operaciones", summary: "Sumar y restar llevando, multiplicar con las tablas y dividir. El orden de las operaciones: primero × y ÷, luego + y −.", flashcards: [{ front: "¿Qué se hace antes, sumar o multiplicar?", back: "Multiplicar. Primero × y ÷, después + y −." }, { front: "7 × 8", back: "56" }, { front: "¿Qué es el doble de un número?", back: "Multiplicarlo por 2." }], quiz: [{ q: "6 × 7 = ?", options: ["42", "48", "36", "49"], answer: 0 }, { q: "En 3 + 2 × 4, ¿qué haces primero?", options: ["3 + 2", "2 × 4", "da igual", "4 − 2"], answer: 1 }, { q: "El doble de 15 es…", options: ["20", "30", "25", "45"], answer: 1 }] },
      { id: "mp2", title: "Fracciones", summary: "Una fracción es una parte de un todo: el de abajo (denominador) dice en cuántas partes se divide y el de arriba (numerador) cuántas tomas.", flashcards: [{ front: "En 3/4, ¿cuál es el numerador?", back: "El 3 (lo que tomas)." }, { front: "1/2 de 10", back: "5" }, { front: "¿Qué fracción es mayor, 1/2 o 1/4?", back: "1/2, porque las partes son más grandes." }], quiz: [{ q: "¿Cuánto es 1/2 de 20?", options: ["5", "10", "15", "2"], answer: 1 }, { q: "En 5/8, el denominador es…", options: ["5", "8", "13", "3"], answer: 1 }, { q: "¿Qué es mayor?", options: ["1/3", "1/2", "1/4", "1/5"], answer: 1 }] },
      { id: "mp3", title: "Geometría y medida", summary: "El perímetro es lo que mide el contorno (se suman los lados). El área es la superficie de dentro. En un cuadrado de lado L: perímetro = 4×L.", flashcards: [{ front: "Perímetro de un cuadrado de lado 5", back: "20 (4 × 5)" }, { front: "¿Qué mide el perímetro?", back: "El contorno, sumando los lados." }, { front: "1 metro = ? cm", back: "100 cm" }], quiz: [{ q: "Perímetro de un cuadrado de lado 3 cm", options: ["6", "9", "12", "3"], answer: 2 }, { q: "1 hora = ? minutos", options: ["100", "60", "90", "120"], answer: 1 }, { q: "El área es…", options: ["el contorno", "la superficie de dentro", "los lados", "la altura"], answer: 1 }] },
    ],
    eso: [
      { id: "me1", title: "Números enteros y racionales", summary: "Los enteros incluyen positivos, negativos y el cero. Regla de signos: (−)·(−)=(+) y (+)·(−)=(−). Las fracciones y decimales son números racionales.", flashcards: [{ front: "(−3) × (−4)", back: "12 (menos por menos da más)" }, { front: "0,75 en fracción", back: "3/4" }, { front: "(+5) × (−2)", back: "−10" }], quiz: [{ q: "(−6) × (−2) = ?", options: ["−12", "12", "−8", "8"], answer: 1 }, { q: "0,5 como fracción es…", options: ["1/2", "1/5", "5/1", "2/1"], answer: 0 }, { q: "(−7) + 3 = ?", options: ["−4", "4", "−10", "10"], answer: 0 }] },
      { id: "me2", title: "Álgebra: ecuaciones", summary: "Una ecuación es una igualdad con una incógnita (x). Para resolverla se despeja la x pasando términos al otro lado cambiando la operación.", flashcards: [{ front: "Resuelve 2x = 10", back: "x = 5" }, { front: "Para quitar un +3, ¿qué haces?", back: "Restar 3 en ambos lados." }, { front: "Resuelve x − 4 = 6", back: "x = 10" }], quiz: [{ q: "2x + 3 = 11. x = ?", options: ["4", "5", "3", "7"], answer: 0 }, { q: "3x = 21. x = ?", options: ["6", "7", "8", "9"], answer: 1 }, { q: "x + 5 = 12. x = ?", options: ["6", "7", "8", "17"], answer: 1 }] },
      { id: "me3", title: "Proporcionalidad y porcentajes", summary: "Un porcentaje es una fracción de 100. El p% de N es N×p/100. La regla de tres relaciona magnitudes proporcionales.", flashcards: [{ front: "25% de 80", back: "20" }, { front: "¿Cómo calculas el 10% de algo?", back: "Dividir entre 10." }, { front: "50% es la…", back: "mitad" }], quiz: [{ q: "20% de 50 = ?", options: ["5", "10", "20", "15"], answer: 1 }, { q: "El 10% de 250 es…", options: ["2,5", "25", "250", "100"], answer: 1 }, { q: "El 50% de 90 es…", options: ["30", "45", "60", "90"], answer: 1 }] },
      { id: "me4", title: "Geometría: áreas y Pitágoras", summary: "Área del triángulo = base×altura/2; del rectángulo = base×altura. Teorema de Pitágoras: en un triángulo rectángulo, h² = c₁² + c₂².", flashcards: [{ front: "Área de triángulo base 6, altura 4", back: "12" }, { front: "Pitágoras", back: "hipotenusa² = cateto² + cateto²" }, { front: "Catetos 3 y 4, hipotenusa", back: "5" }], quiz: [{ q: "Área de un rectángulo 5×4", options: ["9", "20", "18", "25"], answer: 1 }, { q: "Catetos 3 y 4 → hipotenusa", options: ["5", "7", "6", "12"], answer: 0 }, { q: "Área de triángulo base 10 altura 6", options: ["60", "30", "16", "32"], answer: 1 }] },
    ],
    bach: [
      { id: "mb1", title: "Funciones y límites", summary: "Una función relaciona cada x con una y. El límite estudia a qué valor se acerca la función cerca de un punto. La continuidad implica que no hay saltos.", flashcards: [{ front: "f(x)=2x, f(3)", back: "6" }, { front: "¿Qué estudia un límite?", back: "El valor al que tiende la función." }, { front: "Pendiente de y = 3x + 1", back: "3" }], quiz: [{ q: "Si f(x)=x², f(4) = ?", options: ["8", "16", "12", "4"], answer: 1 }, { q: "Pendiente de y = 5x − 2", options: ["−2", "5", "2", "10"], answer: 1 }, { q: "f(x)=x+7, f(0) = ?", options: ["0", "7", "1", "8"], answer: 1 }] },
      { id: "mb2", title: "Derivadas", summary: "La derivada mide la variación de una función. Reglas básicas: la derivada de xⁿ es n·xⁿ⁻¹, y la de una constante es 0.", flashcards: [{ front: "Derivada de x²", back: "2x" }, { front: "Derivada de una constante", back: "0" }, { front: "Derivada de x³", back: "3x²" }], quiz: [{ q: "Derivada de x²", options: ["2x", "x", "2", "x²/2"], answer: 0 }, { q: "Derivada de 7", options: ["7", "0", "1", "x"], answer: 1 }, { q: "Derivada de x⁴", options: ["4x³", "x³", "4x", "3x⁴"], answer: 0 }] },
      { id: "mb3", title: "Probabilidad y estadística", summary: "La probabilidad es casos favorables entre casos posibles. La media es la suma dividida entre el número de datos.", flashcards: [{ front: "P(par en un dado)", back: "3/6 = 1/2" }, { front: "Media de 2, 4, 6", back: "4" }, { front: "P(sacar un 6 en un dado)", back: "1/6" }], quiz: [{ q: "Probabilidad de cara al lanzar una moneda", options: ["1/2", "1/4", "1", "1/6"], answer: 0 }, { q: "Media de 10, 20, 30", options: ["20", "30", "15", "60"], answer: 0 }, { q: "P(número < 3 en un dado)", options: ["2/6", "3/6", "1/6", "4/6"], answer: 0 }] },
    ],
  },

  lengua: {
    primaria: [
      { id: "lp1", title: "La oración: sujeto y predicado", summary: "El sujeto es quien realiza la acción y el predicado es lo que se dice de él (lleva el verbo). Ej: 'El perro (sujeto) corre en el parque (predicado)'.", flashcards: [{ front: "¿Qué tiene siempre el predicado?", back: "El verbo." }, { front: "En 'María canta', ¿el sujeto?", back: "María" }, { front: "¿Quién hace la acción?", back: "El sujeto." }], quiz: [{ q: "En 'El gato duerme', el sujeto es…", options: ["duerme", "El gato", "el", "—"], answer: 1 }, { q: "El predicado siempre lleva…", options: ["sujeto", "verbo", "adjetivo", "artículo"], answer: 1 }, { q: "'Los niños juegan'. Predicado:", options: ["Los niños", "juegan", "Los", "niños"], answer: 1 }] },
      { id: "lp2", title: "Clases de palabras", summary: "El sustantivo nombra (mesa), el adjetivo describe (grande), el verbo expresa acción (correr) y el artículo acompaña al sustantivo (el, la).", flashcards: [{ front: "¿Qué es 'rápido'?", back: "Un adjetivo (describe)." }, { front: "¿Qué es 'saltar'?", back: "Un verbo (acción)." }, { front: "¿Qué es 'casa'?", back: "Un sustantivo (nombra)." }], quiz: [{ q: "'Bonito' es un…", options: ["verbo", "adjetivo", "sustantivo", "artículo"], answer: 1 }, { q: "'Comer' es un…", options: ["sustantivo", "adjetivo", "verbo", "artículo"], answer: 2 }, { q: "'La' es un…", options: ["artículo", "verbo", "adjetivo", "sustantivo"], answer: 0 }] },
      { id: "lp3", title: "Ortografía", summary: "Se escribe 'b' antes de consonante (brazo) y en -bir (escribir). La 'h' es muda. Las palabras agudas llevan tilde si acaban en n, s o vocal.", flashcards: [{ front: "¿'vaca' o 'baca' (animal)?", back: "vaca" }, { front: "¿La h suena?", back: "No, es muda." }, { front: "'camión' lleva tilde porque es…", back: "aguda acabada en n" }], quiz: [{ q: "¿Cómo se escribe el animal?", options: ["baca", "vaca", "vacca", "baka"], answer: 1 }, { q: "Palabra con h muda:", options: ["hola", "ola", "ala", "ojo"], answer: 0 }, { q: "¿Cuál es aguda con tilde?", options: ["casa", "sofá", "mesa", "libro"], answer: 1 }] },
    ],
    eso: [
      { id: "le1", title: "Categorías gramaticales", summary: "Palabras variables: sustantivo, adjetivo, determinante, pronombre, verbo. Invariables: adverbio, preposición, conjunción. El adverbio modifica al verbo (corre rápido).", flashcards: [{ front: "¿'rápidamente' qué es?", back: "Adverbio." }, { front: "Preposición ejemplo", back: "de, a, con, por, para…" }, { front: "¿Qué modifica un adverbio?", back: "Al verbo, adjetivo u otro adverbio." }], quiz: [{ q: "'lentamente' es un…", options: ["adjetivo", "adverbio", "verbo", "nombre"], answer: 1 }, { q: "¿Cuál es preposición?", options: ["correr", "sobre", "bonito", "ellos"], answer: 1 }, { q: "Palabra invariable:", options: ["niño", "alto", "pero", "gato"], answer: 2 }] },
      { id: "le2", title: "Sintaxis de la oración", summary: "La oración se analiza en sujeto y predicado. Dentro del predicado están los complementos: directo (CD), indirecto (CI) y circunstancial (CC).", flashcards: [{ front: "'Compré un libro'. ¿CD?", back: "un libro" }, { front: "El CI suele responder a…", back: "¿a quién? / ¿para quién?" }, { front: "El CC de lugar responde a…", back: "¿dónde?" }], quiz: [{ q: "En 'Leo un cuento', el CD es…", options: ["Leo", "un cuento", "un", "—"], answer: 1 }, { q: "El CC de tiempo responde a…", options: ["¿dónde?", "¿cuándo?", "¿qué?", "¿quién?"], answer: 1 }, { q: "El sujeto de 'Llueve' es…", options: ["Llueve", "no tiene (impersonal)", "yo", "tú"], answer: 1 }] },
      { id: "le3", title: "Tipos de texto y literatura", summary: "Textos narrativos (cuentan hechos), descriptivos (cómo es algo), argumentativos (defienden una idea). Géneros literarios: narrativo, lírico (poesía) y dramático (teatro).", flashcards: [{ front: "¿La poesía es género…?", back: "Lírico." }, { front: "El teatro es género…", back: "Dramático." }, { front: "Un texto que defiende una opinión es…", back: "Argumentativo." }], quiz: [{ q: "El género de la poesía es…", options: ["narrativo", "lírico", "dramático", "técnico"], answer: 1 }, { q: "Una novela pertenece al género…", options: ["lírico", "narrativo", "dramático", "—"], answer: 1 }, { q: "Un texto que describe un paisaje es…", options: ["descriptivo", "argumentativo", "dialogado", "lírico"], answer: 0 }] },
    ],
    bach: [
      { id: "lb1", title: "Movimientos literarios", summary: "La Generación del 98 reflexiona sobre España (Machado, Unamuno). El Romanticismo exalta el sentimiento (Bécquer). El Barroco juega con el lenguaje (Góngora, Quevedo).", flashcards: [{ front: "Bécquer pertenece al…", back: "Romanticismo." }, { front: "Góngora es del…", back: "Barroco (culteranismo)." }, { front: "Tema de la Generación del 98", back: "El problema de España." }], quiz: [{ q: "El Romanticismo exalta…", options: ["la razón", "el sentimiento", "la ciencia", "el orden"], answer: 1 }, { q: "Quevedo pertenece al…", options: ["Barroco", "Realismo", "Vanguardias", "Ilustración"], answer: 0 }, { q: "Antonio Machado es de la Generación del…", options: ["27", "98", "50", "14"], answer: 1 }] },
      { id: "lb2", title: "Comentario de texto", summary: "Un comentario identifica el tema, la estructura, el tipo de texto y los recursos literarios (metáfora, hipérbole, personificación) y valora el estilo del autor.", flashcards: [{ front: "Comparar sin 'como' es…", back: "Metáfora." }, { front: "Exagerar es…", back: "Hipérbole." }, { front: "Dar cualidades humanas a algo es…", back: "Personificación." }], quiz: [{ q: "'Sus ojos son dos luceros' es una…", options: ["metáfora", "hipérbole", "ironía", "rima"], answer: 0 }, { q: "Exagerar mucho es una…", options: ["metáfora", "hipérbole", "elipsis", "anáfora"], answer: 1 }, { q: "'El viento susurraba' es…", options: ["personificación", "símil", "metonimia", "hipérbaton"], answer: 0 }] },
    ],
  },

  ingles: {
    primaria: [
      { id: "ip1", title: "Present Simple", summary: "Se usa para rutinas y hechos. En 3ª persona (he/she/it) el verbo añade -s: 'She plays'. Negativa con don't/doesn't.", flashcards: [{ front: "She ___ (play) football", back: "plays" }, { front: "Negative of 'I like'", back: "I don't like" }, { front: "He ___ (go) to school", back: "goes" }], quiz: [{ q: "She ___ tennis.", options: ["play", "plays", "playing", "to play"], answer: 1 }, { q: "Negative: 'They like it' →", options: ["They don't like it", "They doesn't like it", "They not like it", "They no like it"], answer: 0 }, { q: "He ___ TV every day.", options: ["watch", "watchs", "watches", "watching"], answer: 2 }] },
      { id: "ip2", title: "There is / There are", summary: "'There is' para singular (There is a cat) y 'There are' para plural (There are two cats). Preguntas: Is there…? / Are there…?", flashcards: [{ front: "___ a book on the table", back: "There is" }, { front: "___ three apples", back: "There are" }, { front: "Question for plural", back: "Are there…?" }], quiz: [{ q: "___ two dogs.", options: ["There is", "There are", "There be", "It is"], answer: 1 }, { q: "___ a pen here.", options: ["There are", "There is", "There be", "Have"], answer: 1 }, { q: "Plural question:", options: ["Is there?", "Are there?", "There is?", "Be there?"], answer: 1 }] },
    ],
    eso: [
      { id: "ie1", title: "Present Perfect", summary: "Have/has + participio. Se usa para experiencias y acciones recientes con resultado en el presente: 'I have finished'. Marcadores: ever, never, just, already, yet.", flashcards: [{ front: "I ___ (see) that film", back: "have seen" }, { front: "'just' va…", back: "entre have y el participio" }, { front: "Past participle of 'go'", back: "gone" }], quiz: [{ q: "I have ___ my homework.", options: ["do", "did", "done", "doing"], answer: 2 }, { q: "She has ___ to London.", options: ["go", "went", "gone", "going"], answer: 2 }, { q: "Marker for Present Perfect:", options: ["yesterday", "already", "last week", "ago"], answer: 1 }] },
      { id: "ie2", title: "Conditionals", summary: "First conditional (real): If + present, will + verb ('If it rains, I will stay'). Second conditional (irreal): If + past, would + verb ('If I were rich…').", flashcards: [{ front: "If it rains, I ___ stay", back: "will" }, { front: "Second conditional uses…", back: "If + past, would + verb" }, { front: "If I ___ you (be)…", back: "were" }], quiz: [{ q: "If you study, you ___ pass.", options: ["will", "would", "are", "do"], answer: 0 }, { q: "If I had money, I ___ travel.", options: ["will", "would", "am", "do"], answer: 1 }, { q: "First conditional: If + ___ , will…", options: ["past", "present", "future", "would"], answer: 1 }] },
    ],
    bach: [
      { id: "ib1", title: "Passive & Reported Speech", summary: "Pasiva: be + participio ('The cake was eaten'). Estilo indirecto: los tiempos retroceden ('I am tired' → He said he was tired).", flashcards: [{ front: "Active 'They build houses' → passive", back: "Houses are built." }, { front: "'I will go' reported →", back: "He said he would go." }, { front: "Passive structure", back: "be + past participle" }], quiz: [{ q: "Passive of 'She writes a letter':", options: ["A letter is written", "A letter writes", "A letter was write", "Is written a letter"], answer: 0 }, { q: "'I am happy' reported: He said he ___ happy.", options: ["is", "was", "be", "were"], answer: 1 }, { q: "Passive uses verb…", options: ["have", "be + participle", "do", "will"], answer: 1 }] },
    ],
  },

  sociales: {
    primaria: [
      { id: "sp1", title: "El relieve y los ríos de España", summary: "España tiene mesetas, montañas (Pirineos, Sierra Nevada) y costas. Ríos principales: Ebro, Tajo, Duero, Guadalquivir. La mayoría desemboca en el Atlántico.", flashcards: [{ front: "Río que pasa por Sevilla", back: "Guadalquivir" }, { front: "Montañas entre España y Francia", back: "Pirineos" }, { front: "Río más largo de España", back: "Tajo" }], quiz: [{ q: "El río de Sevilla es el…", options: ["Ebro", "Guadalquivir", "Duero", "Tajo"], answer: 1 }, { q: "Los Pirineos separan España de…", options: ["Portugal", "Francia", "Italia", "Marruecos"], answer: 1 }, { q: "El Ebro desemboca en el mar…", options: ["Atlántico", "Mediterráneo", "Cantábrico", "Negro"], answer: 1 }] },
      { id: "sp2", title: "Prehistoria y Edad Antigua", summary: "La Prehistoria va hasta la escritura: Paleolítico (caza), Neolítico (agricultura). En la Edad Antigua, Roma dominó Hispania y nos dejó el latín, las leyes y las calzadas.", flashcards: [{ front: "El Neolítico inventa…", back: "La agricultura y la ganadería." }, { front: "¿Qué pueblo dominó Hispania?", back: "Los romanos." }, { front: "La Prehistoria acaba con…", back: "La invención de la escritura." }], quiz: [{ q: "En el Paleolítico vivían de…", options: ["la agricultura", "la caza y recolección", "el comercio", "la industria"], answer: 1 }, { q: "Hispania fue dominada por…", options: ["los griegos", "los romanos", "los egipcios", "los vikingos"], answer: 1 }, { q: "El Neolítico empieza con…", options: ["el fuego", "la agricultura", "la rueda", "la escritura"], answer: 1 }] },
    ],
    eso: [
      { id: "se1", title: "La Edad Media", summary: "Tras la caída de Roma surge el feudalismo: señores, vasallos y siervos. En la Península conviven cristianos, musulmanes (Al-Ándalus) y judíos. La Reconquista termina en 1492.", flashcards: [{ front: "Al-Ándalus era el territorio…", back: "musulmán de la Península." }, { front: "La Reconquista acaba en…", back: "1492 (Granada)." }, { front: "Base de la economía feudal", back: "La agricultura." }], quiz: [{ q: "La Reconquista terminó en…", options: ["1492", "1808", "1212", "711"], answer: 0 }, { q: "El sistema medieval se llama…", options: ["capitalismo", "feudalismo", "comunismo", "imperio"], answer: 1 }, { q: "Al-Ándalus era de cultura…", options: ["cristiana", "musulmana", "romana", "griega"], answer: 1 }] },
      { id: "se2", title: "Edad Moderna", summary: "En 1492 Colón llega a América y empieza la Edad Moderna. El Renacimiento recupera la cultura clásica. España vive su Siglo de Oro con un gran imperio.", flashcards: [{ front: "¿Año del descubrimiento de América?", back: "1492" }, { front: "El Renacimiento se inspira en…", back: "Grecia y Roma." }, { front: "Reyes que financiaron a Colón", back: "Los Reyes Católicos." }], quiz: [{ q: "Colón llegó a América en…", options: ["1492", "1500", "1469", "1592"], answer: 0 }, { q: "El Renacimiento nació en…", options: ["Francia", "Italia", "Inglaterra", "Portugal"], answer: 1 }, { q: "El Siglo de Oro fue una época de…", options: ["crisis económica", "esplendor cultural", "guerra civil", "industrialización"], answer: 1 }] },
      { id: "se3", title: "Geografía: clima y población", summary: "España tiene clima mediterráneo, oceánico (norte) y de montaña. La población se concentra en las costas y grandes ciudades; el interior está más despoblado.", flashcards: [{ front: "Clima del norte de España", back: "Oceánico (lluvioso)." }, { front: "¿Dónde vive más gente?", back: "En las costas y ciudades." }, { front: "Clima de la mayor parte de España", back: "Mediterráneo." }], quiz: [{ q: "El clima del norte es…", options: ["desértico", "oceánico", "tropical", "polar"], answer: 1 }, { q: "La población se concentra en…", options: ["el interior", "las costas", "la montaña", "los ríos"], answer: 1 }, { q: "El clima mediterráneo tiene veranos…", options: ["fríos", "secos y calurosos", "lluviosos", "nevados"], answer: 1 }] },
    ],
  },

  ciencias: {
    primaria: [
      { id: "cp1", title: "Los seres vivos", summary: "Los seres vivos nacen, crecen, se reproducen y mueren. Se clasifican en cinco reinos: animales, plantas, hongos, protozoos y bacterias. Las plantas fabrican su alimento con la fotosíntesis.", flashcards: [{ front: "¿Cómo se alimentan las plantas?", back: "Por la fotosíntesis." }, { front: "Funciones vitales", back: "Nutrición, relación y reproducción." }, { front: "¿Cuántos reinos hay?", back: "Cinco." }], quiz: [{ q: "Las plantas fabrican su alimento mediante…", options: ["respiración", "fotosíntesis", "digestión", "circulación"], answer: 1 }, { q: "¿Cuál NO es función vital?", options: ["nutrición", "relación", "reproducción", "televisión"], answer: 3 }, { q: "El reino de los perros es…", options: ["plantas", "animales", "hongos", "bacterias"], answer: 1 }] },
      { id: "cp2", title: "El cuerpo humano", summary: "El aparato digestivo procesa la comida, el respiratorio toma oxígeno y el circulatorio (corazón) lleva la sangre. El esqueleto nos sostiene y los músculos nos mueven.", flashcards: [{ front: "Órgano que bombea sangre", back: "El corazón." }, { front: "¿Qué tomamos al respirar?", back: "Oxígeno." }, { front: "¿Qué nos sostiene?", back: "El esqueleto (los huesos)." }], quiz: [{ q: "El corazón pertenece al aparato…", options: ["digestivo", "circulatorio", "respiratorio", "nervioso"], answer: 1 }, { q: "Respiramos para tomar…", options: ["agua", "oxígeno", "comida", "luz"], answer: 1 }, { q: "Los huesos forman el…", options: ["músculo", "esqueleto", "cerebro", "pulmón"], answer: 1 }] },
    ],
    eso: [
      { id: "ce1", title: "La célula", summary: "La célula es la unidad de vida. Las procariotas (bacterias) no tienen núcleo; las eucariotas (animales y plantas) sí. La célula vegetal tiene pared y cloroplastos.", flashcards: [{ front: "¿Qué célula tiene núcleo?", back: "La eucariota." }, { front: "Orgánulo de la fotosíntesis", back: "El cloroplasto." }, { front: "La célula vegetal tiene… (y la animal no)", back: "Pared celular y cloroplastos." }], quiz: [{ q: "Las bacterias son células…", options: ["eucariotas", "procariotas", "vegetales", "muertas"], answer: 1 }, { q: "La fotosíntesis ocurre en el…", options: ["núcleo", "cloroplasto", "ribosoma", "vacuola"], answer: 1 }, { q: "Tienen pared celular las células…", options: ["animales", "vegetales", "nerviosas", "musculares"], answer: 1 }] },
      { id: "ce2", title: "La materia: átomos", summary: "Todo está formado por átomos. El átomo tiene protones (+), neutrones y electrones (−). Los estados de la materia son sólido, líquido y gaseoso.", flashcards: [{ front: "Carga del protón", back: "Positiva (+)." }, { front: "Carga del electrón", back: "Negativa (−)." }, { front: "Estados de la materia", back: "Sólido, líquido y gaseoso." }], quiz: [{ q: "El electrón tiene carga…", options: ["positiva", "negativa", "neutra", "ninguna"], answer: 1 }, { q: "El paso de líquido a gas es la…", options: ["fusión", "evaporación", "solidificación", "condensación"], answer: 1 }, { q: "El núcleo del átomo tiene…", options: ["electrones", "protones y neutrones", "solo electrones", "nada"], answer: 1 }] },
      { id: "ce3", title: "Fuerzas y energía", summary: "Una fuerza puede mover o deformar. La energía ni se crea ni se destruye, se transforma. La velocidad = espacio / tiempo.", flashcards: [{ front: "Velocidad = ?", back: "espacio / tiempo" }, { front: "¿La energía se destruye?", back: "No, se transforma." }, { front: "Unidad de fuerza", back: "El newton (N)." }], quiz: [{ q: "La velocidad se calcula como…", options: ["espacio × tiempo", "espacio / tiempo", "tiempo / espacio", "fuerza × masa"], answer: 1 }, { q: "La energía…", options: ["se crea", "se destruye", "se transforma", "desaparece"], answer: 2 }, { q: "La fuerza se mide en…", options: ["metros", "newtons", "litros", "vatios"], answer: 1 }] },
    ],
    bach: [
      { id: "cb1", title: "Genética", summary: "El ADN guarda la información hereditaria en genes. Mendel describió cómo se heredan los caracteres: dominantes (se manifiestan) y recesivos.", flashcards: [{ front: "¿Dónde está la información genética?", back: "En el ADN." }, { front: "Un alelo que se manifiesta es…", back: "Dominante." }, { front: "Las leyes de la herencia las formuló…", back: "Mendel." }], quiz: [{ q: "La información hereditaria está en el…", options: ["ARN", "ADN", "ATP", "ribosoma"], answer: 1 }, { q: "Un gen que se manifiesta siempre es…", options: ["recesivo", "dominante", "neutro", "mutado"], answer: 1 }, { q: "Las leyes de la herencia son de…", options: ["Darwin", "Mendel", "Watson", "Pasteur"], answer: 1 }] },
      { id: "cb2", title: "Reacciones químicas", summary: "En una reacción los reactivos se transforman en productos. La masa se conserva (Lavoisier). Hay que ajustar las ecuaciones para igualar los átomos de cada lado.", flashcards: [{ front: "Ley de conservación de la masa", back: "La masa no cambia (Lavoisier)." }, { front: "Reactivos →", back: "Productos." }, { front: "¿Para qué se ajusta una ecuación?", back: "Para igualar los átomos a ambos lados." }], quiz: [{ q: "En una reacción, la masa total…", options: ["aumenta", "se conserva", "disminuye", "desaparece"], answer: 1 }, { q: "Lo que se transforma son los…", options: ["productos", "reactivos", "catalizadores", "gases"], answer: 1 }, { q: "La conservación de la masa es ley de…", options: ["Newton", "Lavoisier", "Ohm", "Mendel"], answer: 1 }] },
    ],
  },

  general: {
    eso: [
      { id: "ge1", title: "Técnicas de estudio", summary: "Subraya las ideas clave, haz esquemas y resúmenes, y repasa con tarjetas. Estudiar poco cada día (repaso espaciado) funciona mejor que mucho de golpe.", flashcards: [{ front: "¿Mejor estudiar todo de golpe o repartido?", back: "Repartido (repaso espaciado)." }, { front: "Primer paso al estudiar un tema", back: "Leer y subrayar lo importante." }, { front: "Herramienta para memorizar", back: "Las tarjetas (flashcards)." }], quiz: [{ q: "El repaso espaciado consiste en…", options: ["estudiar todo la noche antes", "repartir el estudio en días", "no repasar", "copiar"], answer: 1 }, { q: "Un buen resumen incluye…", options: ["todo el texto", "solo las ideas clave", "dibujos", "nada"], answer: 1 }, { q: "Para memorizar datos van bien…", options: ["las tarjetas", "ver la tele", "dormir", "el móvil"], answer: 0 }] },
    ],
  },
};

export function getUnits(name: string, level: string): Unit[] {
  const g = detectGroup(name);
  const b = detectBand(level);
  return CURR[g][b] || CURR[g].eso || CURR[g].primaria || CURR.general.eso || [];
}
